export enum ListaTopDez {
    TOP_DEZ_PERDEDORES = 'TOP_DEZ_PERDEDORES',
    ITENS_MAIS_PERDIDOS = 'ITENS_MAIS_PERDIDOS',
    ITENS_MAIS_PERDIDOS_HOMEM = 'ITENS_MAIS_PERDIDOS_HOMEM',
    ITENS_MAIS_PERDIDOS_MULHERES = 'ITENS_MAIS_PERDIDOS_MULHERES',
    ITENS_MAIS_PERDIDOS_SEMANA = 'ITENS_MAIS_PERDIDOS_SEMANA',
    ITENS_MAIS_PERDIDOS_MES = 'ITENS_MAIS_PERDIDOS_MES',
}
